from django.urls import path

from . import views

urlpatterns = [
       path('register', views.register, name='register'),
       path('create_account', views.create_account, name='create_account'),
       path('link_account', views.link_account, name='link_account'),
       path('otp', views.otp, name='otp'),
       path('confirm_otp', views.confirm_otp, name='confirm_otp'),
       path('logout1', views.logout1, name='logout1'),
       path('pin', views.pin, name='pin'),
       path('transaction', views.transaction, name='transaction'),
       path('show_coupons', views.show_coupons, name='show_coupons'),
       path('view_coupon', views.view_coupon, name='view_coupon'),
       path('Payment_history', views.Payment_history, name='Payment_history'),
       path('individual_paymenthist', views.individual_paymenthist, name='individual_paymenthist'),
       path('dropdown', views.dropdown, name='dropdown'),
       path('branch_name', views.branch_name, name='branch_name'),
       path('check_balance', views.check_balance, name='check_balance'),
       path('edit_pin', views.edit_pin, name='edit_pin'),
       path('split_bill', views.split_bill, name='split_bill'),
       path('splitbill_groups', views.splitbill_groups, name='splitbill_groups'),
       path('individual_notification', views.individual_notification, name='individual_notification'),
       path('show_data', views.show_data, name='show_data'),
       path('pay_splitbill', views.pay_splitbill, name='pay_splitbill'),
       path('messages', views.messages, name='messages'),
       path('individual_messages', views.individual_messages, name='individual_messages'),
       path('profile', views.profile, name='profile'),
       path('dynamicpanel', views.dynamicpanel, name='dynamicpanel'),
       path('otp_wallet', views.otp_wallet, name='otp_wallet'),
       path('confirmotp_wallet', views.confirmotp_wallet, name='confirmotp_wallet'),
       path('activate_wallet', views.activate_wallet, name='activate_wallet'),
       path('continue1', views.continue1, name='continue1'),
       path('autoincrement_wallet', views.autoincrement_wallet, name='autoincrement_wallet'),
       path('increment_wallet', views.increment_wallet, name='increment_wallet'),
       path('deactivate', views.deactivate, name='deactivate'),
       path('activate_postpaid', views.activate_postpaid, name='activate_postpaid'),
       path('confirmotp_postpaid', views.confirmotp_postpaid, name='confirmotp_postpaid'),
       path('cibil_score', views.cibil_score, name='cibil_score'),
       path('login_page', views.login_page, name='login_page'),
]
