# Generated by Django 2.2 on 2023-10-15 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('nominee', models.CharField(blank=True, max_length=120, null=True)),
                ('nominee_phoneno', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to='')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='')),
                ('aadhaar_card_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pan_card_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Pictures/')),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('UPI_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('UPI_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('PIN', models.IntegerField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BankAccount',
            },
        ),
    ]
