# Generated by Django 2.2 on 2023-10-15 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('PIN', models.IntegerField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LinkedAccount',
            },
        ),
    ]
