# Generated by Django 2.2 on 2023-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_linkedaccount_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='cashback',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
