# Generated by Django 2.2 on 2023-10-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_transactions_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cashback',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
