# Generated by Django 2.2 on 2023-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20231019_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('offer', models.CharField(blank=True, max_length=200, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Scratch_cards',
            },
        ),
    ]
