# Generated by Django 2.2 on 2023-10-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Coupons'),
        ),
    ]
