# Generated by Django 2.2 on 2023-10-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_transactions_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.SplitBill')),
            ],
            options={
                'db_table': 'Split_Bill',
            },
        ),
    ]
