# Generated by Django 2.2 on 2023-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_splitbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitbill',
            name='admin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='splitbill',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
