# Generated by Django 2.2 on 2023-10-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20231020_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Dropdowns')),
            ],
            options={
                'db_table': 'Dropdowns',
            },
        ),
    ]
