# Generated by Django 2.2 on 2023-10-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20231020_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
