# Generated by Django 2.2 on 2023-10-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_otp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdowns',
            old_name='delete',
            new_name='delete1',
        ),
    ]
