# Generated by Django 2.2 on 2023-10-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20231021_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdowns',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
