# Generated by Django 2.2 on 2023-10-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20231021_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
