# Generated by Django 2.2 on 2023-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20231022_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='UPI_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
