# Generated by Django 2.2 on 2023-10-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_transactions_upi_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitbill',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
