# Generated by Django 2.2 on 2023-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_splitbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
