# Generated by Django 2.2 on 2023-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_linkedaccount_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='dynamic_panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('delete', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'dynamic_panel',
            },
        ),
    ]
