# Generated by Django 2.2 on 2023-10-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_dynamic_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic_panel',
            old_name='delete',
            new_name='delete1',
        ),
        migrations.RemoveField(
            model_name='dynamic_panel',
            name='order',
        ),
        migrations.AddField(
            model_name='dynamic_panel',
            name='order1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='dynamic_panel',
            table='Dynamic_panel',
        ),
    ]
