# Generated by Django 2.2 on 2023-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20231023_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='wallet',
            field=models.CharField(blank=True, default='False', max_length=20),
        ),
    ]
