# Generated by Django 2.2 on 2023-10-24 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_otp_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('deactivate', models.CharField(blank=True, default='False', max_length=20)),
                ('less_than', models.IntegerField(blank=True, null=True)),
                ('increase_by', models.IntegerField(blank=True, null=True)),
                ('account1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.BankAccount')),
                ('account2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.LinkedAccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
