# Generated by Django 2.2 on 2023-10-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='wallet',
            new_name='wallet1',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='Wallet',
        ),
    ]
