# Generated by Django 2.2 on 2023-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20231024_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='autoincrement',
            field=models.CharField(blank=True, default='False', max_length=20),
        ),
    ]
