# Generated by Django 2.2 on 2023-10-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_wallet_autoincrement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupons',
            table='Coupons',
        ),
    ]
