# Generated by Django 2.2 on 2023-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20231025_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='wallet1',
        ),
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(blank=True, default='Login', max_length=20),
        ),
    ]
