# Generated by Django 2.2 on 2023-10-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20231026_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactivate', models.CharField(blank=True, default='False', max_length=20)),
                ('CIBIL_Score', models.IntegerField(blank=True, null=True)),
                ('Credit_Limit', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('account1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.BankAccount')),
                ('account2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.LinkedAccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PostPaid',
            },
        ),
    ]
