# Generated by Django 2.2 on 2023-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20231026_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaid',
            name='aadhaar_card_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='CIBIL_Score',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='Credit_Limit',
            field=models.IntegerField(blank=True, default=60000, null=True),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='balance',
            field=models.IntegerField(blank=True, default=60000, null=True),
        ),
    ]
