# Generated by Django 2.2 on 2023-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20231026_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitbill',
            name='indiv_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
