# Generated by Django 2.2 on 2023-10-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_splitbill_indiv_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic_panel',
            name='state1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
