# Generated by Django 2.2 on 2023-10-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_auto_20231028_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpaid',
            name='balance',
        ),
        migrations.AddField(
            model_name='postpaid',
            name='bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postpaid',
            name='penality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postpaid',
            name='penality_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='Credit_Limit',
            field=models.IntegerField(blank=True, default=6000, null=True),
        ),
    ]
