# Generated by Django 2.2 on 2023-10-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20231029_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic_panel',
            name='icon',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
